// NON - BLOCKING CODE => BLOCK THE FLOW OF THE PROGRAM => READ FILE SYNC 


// BLOCKING CODE => DOES NOT BLOCK EXECUTION => READ FILE ASYNC


// DEPENDS ON THE USE CASE AND BOTH ARE REALLY IMPORTANT .

// DIFF BW QUEUE AND STACK 

// QUEUE IS JUST LIKE A LINE OF DRIVE THRU IN MC'D WHERE ONE BY ONE AS THE ORDER IS COMPLETED IS SENT OUT 

// STACK MEANS THE LAST ONE THAT ENTERED WILL BE DONE FIRST LIKE STACKING OF EMERGENCY  TASKS UPON NORMAL TASKS